# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: battery.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'battery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbattery.proto\x12\x1eservices.vehiclestates.battery\",\n\x11GetBatteryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\xe7\x02\n\x07\x42\x61ttery\x12=\n\nupdateTime\x18\x01 \x01(\x0b\x32).services.vehiclestates.battery.Timestamp\x12$\n\x1c\x62\x61tteryChargeLevelPercentage\x18\x02 \x01(\x01\x12+\n#averageEnergyConsumptionKwhPer100Km\x18\x03 \x01(\x01\x12\"\n\x1a\x65stimatedDistanceToEmptyKm\x18\x04 \x01(\x05\x12*\n\"estimatedChargingTimeToFullMinutes\x18\x05 \x01(\x05\x12\x1f\n\x17\x63hargerConnectionStatus\x18\x06 \x01(\x05\x12\x16\n\x0e\x63hargingStatus\x18\x07 \x01(\x05\x12%\n\x1d\x65stimatedDistanceToEmptyMiles\x18\x08 \x01(\x05\x12\x1a\n\x12\x63hargingPowerWatts\x18\n \x01(\x05\"g\n\x12GetBatteryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x38\n\x07\x62\x61ttery\x18\x03 \x01(\x0b\x32\'.services.vehiclestates.battery.Battery2\x8f\x01\n\x0e\x42\x61tteryService\x12}\n\x10GetLatestBattery\x12\x31.services.vehiclestates.battery.GetBatteryRequest\x1a\x32.services.vehiclestates.battery.GetBatteryResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBATTERYREQUEST']._serialized_start=49
  _globals['_GETBATTERYREQUEST']._serialized_end=93
  _globals['_TIMESTAMP']._serialized_start=95
  _globals['_TIMESTAMP']._serialized_end=138
  _globals['_BATTERY']._serialized_start=141
  _globals['_BATTERY']._serialized_end=500
  _globals['_GETBATTERYRESPONSE']._serialized_start=502
  _globals['_GETBATTERYRESPONSE']._serialized_end=605
  _globals['_BATTERYSERVICE']._serialized_start=608
  _globals['_BATTERYSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
