name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: ZIP Component Dir
        run: |
          cd "${GITHUB_WORKSPACE}/custom_components/volvooncall_cn"
          zip -r /tmp/volvooncall_cn.zip ./

      - name: Upload zip to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload "${GITHUB_REF_NAME}"
          /tmp/volvooncall_cn.zip
          --clobber
          --repo "${GITHUB_REPOSITORY}"
