name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/volvooncall_cn
          zip -r volvooncall_cn.zip ./

      - name: Upload zip to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload "${{ github.event.release.tag_name }}"
          "${{ github.workspace }}/custom_components/volvooncall_cn/volvooncall_cn.zip"
          --clobber
